networks:
  palm-backend:
    external: false

services:
  db:
    image: "postgres:18"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    
    volumes:
      - ./postgres:/var/lib/postgresql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    networks:
      - palm-backend

  rust:
    container_name: rust
    image: palm-backend:local
    build:
      context: ./palm-backend/
      dockerfile: rust.dockerfile
    environment:
      DATABASE_CREDS: postgres://username:password@db:5432/palm
    ports:
      - "9000:3000"
    depends_on:
      - db
    networks:
      - palm-backend
